### ISSUE TITLE
Empty hdf file

### ISSUE THREAD

**Issue by zxdawn** [ZPYin/Radiosonde#2]
Hi, I tried to run the radiosonde.py using the default settings, but the `temp.h5` file is empty. Is there anything I should modify? Thanks!

**Comment by ZPYin** [comment]
Could you check the file size to confirm that it's empty? 

For me, it still works as expected. Or you can start debugging to see whether the radiosonde profile was parsed correctly.

**Comment by zxdawn** [comment]
The size is 16K which only has the variable names without any data (Screenshot of HDFView):
![image](https://user-images.githubusercontent.com/30388627/173026469-8d8a7178-051c-400b-bd61-659cada3a18f.png)


But, the `data` returned by the `GetRSData` function looks fine:
```
[(1000. ,    35.,  22.8,  10.2, 45., 7.83, 348.,  1.944 , 295.9, 318.9, 297.3)
 ( 998.1,    53.,  23.9,   6. , 32., 5.88, 348.,  3.1104, 297.2, 314.7, 298.3)
 ( 991.1,   114.,  24.5,   4.8, 28., 5.44, 348.,  6.9984, 298.4, 314.8, 299.4)
 ( 987.7,   150.,  24.2,   4.5, 28., 5.35, 348.,  9.1368, 298.4, 314.5, 299.4)
....
```

**Comment by ZPYin** [comment]
I tried to open the data file with HDFView... But failed. So I cannot dig into this issue.

From my side, everything just works fine. I can check variable inside the HDF5 file with [Panoply](https://www.giss.nasa.gov/tools/panoply/).


And I should point out that the objective of this tiny project is to provide a handy tool for people to obtain radiosonde data. Because for many of them, parsing data from the internet is not that straightforward. So, if you can get data correctly, it means this tool did its job. Regarding saving the data into any sort of data formats, you can choose the way that you like.   😃

**Comment by zxdawn** [comment]
Thanks. BTW, it seems the csv format is better to save this kind of data. HDF and NETCDF are more suitable for multidimensional data.
